zomato 
CREATE TABLE USERS
(
	USER_ID DECIMAL(13,0)
	,USER_TYPE DECIMAL(13,0) 
	,USER_NAME VARCHAR(25) 
	,PASSWORD VARCHAR(50)
	,CONTACT DECIMAL(10,0)
	,PRIMARY KEY(USER_ID)
	
);

CREATE TABLE ZOMATO_ADDRESS
(
	ADDRESS_ID DECIMAL(13,0)
	,USER_ID DECIMAL(13,0)
	,ADDRESS_NAME VARCHAR(200)
	,ADDRESS1 VARCHAR(200)
	,ADDRESS2 VARCHAR(200)
	,ADDRESS3 VARCHAR(200)
	,ZIPCODE DECIMAL(10,0)
	,STATE VARCHAR(200)
	,CITY VARCHAR(200)
	,COUNTRY VARCHAR(200)
	,PRIMARY KEY (ADDRESS_ID)
	,CONSTRAINT ZOMATO_ADDRESS_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE HOTEL
(
	USER_ID DECIMAL(13,0)
	,USER_NAME VARCHAR(200)
	,RATING DECIMAL(2)
	,FEEDBACK_COMMENTS VARCHAR(300)
	,PRIMARY KEY (USER_ID)
	,CONSTRAINT HOTEL_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
insert into hotel values(101,'Lavi',5,'');

CREATE TABLE MENU
	(
		USER_ID DECIMAL(13,0)
		,ITEM_ID DECIMAL(13,0)
		,ITEM_NAME VARCHAR(200)
		,ITEM_COST DECIMAL(13,2)
		,IN_STOCK DECIMAL(1,0)
		,DISCOUNT DECIMAL(5,2)
		,PRIMARY KEY (ITEM_ID, USER_ID)
		,CONSTRAINT MENU_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) 
	);
	insert into menu values(101,101,'Butter Chicken',150,1,10)
	
		CREATE TABLE ZOMATO_ORDER
	(
		ORDER_ID DECIMAL(13,0)
		,DATE DATETIME
		,COST DECIMAL(13,2)
		,USER_ID_CUST DECIMAL(13,0)
		,USER_ID_HOTEL DECIMAL(13,0)
		,PRIMARY KEY(ORDER_ID)
		,CONSTRAINT ORDER_1 FOREIGN KEY(USER_ID_CUST) REFERENCES USERS(USER_ID) 
		,CONSTRAINT ORDER_2 FOREIGN KEY(USER_ID_HOTEL) REFERENCES USERS(USER_ID) 
	);
	insert into zomato_order values (101,now(),300,101,101);
	
	CREATE TABLE ZOMATO_ORDER_DETAIL
	(
		ORDER_ID DECIMAL(13,0)
		,ITEM_ID DECIMAL(13,0) 
		,QTY DECIMAL(5,0)
		,ITEM_COST DECIMAL(13,2)
		,PRIMARY KEY (ORDER_ID, ITEM_ID)
		,CONSTRAINT ZOMATO_ORDER_DETAIL_1 FOREIGN KEY(ORDER_ID) REFERENCES ZOMATO_ORDER(ORDER_ID)
		,CONSTRAINT ZOMATO_ORDER_DETAIL_2 FOREIGN KEY(ITEM_ID) REFERENCES MENU(ITEM_ID)
	);
	
	insert into ZOMATO_ORDER_DETAIL values(101,101,5,500);
	
	CREATE TABLE ZOMATO_CART
	(
		USER_ID DECIMAL(13,0)
		,ITEM_ID DECIMAL(13,0)
		,QTY DECIMAL(5,0)
		,FINAL_COST DECIMAL(13,2)
		,PRIMARY KEY(USER_ID, ITEM_ID)
		,CONSTRAINT ZOMATO_CART_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) 
	);
	
	INSERT INTO ZOMATO_CART VALUES (101,101,5,1000);
	
	
	
	login-> get a list of restos-> view menu -> add item in cart-> go to cart-> place order